# Generated by Django 2.2.4 on 2020-04-30 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlistsApp', '0002_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='playlistsApp.User'),
        ),
    ]
